name: flutter_myapp
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.11
  firebase_core: ^1.14.0
  provider : ^6.0.2
  google_sign_in : ^5.2.4
  font_awesome_flutter : ^10.1.0
  google_fonts: ^2.3.1
  flutter_facebook_login: ^3.0.0
  flutter_spinkit: 5.1.0
  maps_launcher: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/back1.jpg
    - images/marguerittes.png
    - images/barbeque.png
    - images/Vegetariane.png
    - images/tandoori.png
    - images/cocacola.png
    - images/sevenup.png
    - images/fanta.png
    - images/pepsi.png
    - images/user.png
    - images/buy.png
    - images/home.png
    - images/profile.png
    - images/cart.png
    - images/map.png
    - images/user2.png
    - images/back2.jpg
    - images/logo.png
    - images/one_click.png








  fonts:
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat.ttf


